config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end
  
  def show
    @article = Article.find(params[:id])
  end

  def new
  end
  
  def create
      @article = Article.new(article_params)
      @article.save
      
      # /articles/new にリダイレクト
      redirect_to @article
  end
    
  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render :inline => "<i>hello</i>"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= link_to article.title, article %></td>
      <td><%= article.body %></td>
    </tr>
  <% end %>

</table>

<%= link_to 'New article', new_article_path %>

app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do |f| %>
  <div>
    <div><%= f.label :title %></div>
    <div><%= f.text_field :title %></div>
 
    <div><%= f.label :body %></div>
    <div><%= f.text_area :body %></div>

    <div><%= f.submit %></div>
  </div>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div>
  <strong>Title:</strong>
  <%= @article.title %>
</div>
 
<div>
  <strong>Text:</strong>
  <%= @article.body %>
</div>

<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello world!</h1>